#!/usr/bin/env ruby

require 'fileutils'

class File
  def self.open_and_process(*args)
    f = File.open(*args)
    yield f
    f.close()
  end
end

v = ARGV[0]

RESOLVE_FILE = '/etc/resolv.conf'

FileUtils.copy(RESOLVE_FILE, "#{RESOLVE_FILE}.bak")

BOILER_PLATE = %{
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated .. by morgan:resolve_toggle.rb
#
}

DOMAIN_LINE = 'domain bgchnet.co.uk'

am_dns = ['172.19.1.100', '10.240.11.100']
google_dns = ['8.8.8.8', '8.8.4.4']

dnss =[am_dns, google_dns]

File.open_and_process(RESOLVE_FILE, 'w') do |f|
  f.write(BOILER_PLATE)
  f.write(DOMAIN_LINE)

  if v
    dnss.reverse!
  end

  dnss.to_enum.each do |d|
    d.to_enum.each do |l|
      f.write "nameserver #{l.to_s}\n"
    end
  end
end